### ISSUE TITLE
[Admin] Notes from meetings - Issue or doc?

### ISSUE THREAD

**Issue by twhyntie** [OpenCosmics/opencosmics.github.io#14]
Thanks for a great meeting today (especially at short notice - my fault for pseudo-randomly dropping into CERN!).

Quick question - would meeting notes be better as Issues, or with their own file in something like:

`meetings/2016-05-04/NOTES.md`

What do projects normally do, @RaoOfPhysics?

**Comment by RaoOfPhysics** [comment]
Hmm. Worth thinking about and I don't want to impose anything here. For some food for thought, here's how we run the CERN Study Group:
- "[For Info](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues?utf8=%E2%9C%93&q=label%3A%22For+info%22+)" issues have things like:
  - [Intros](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/26)
  - [Project lists](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/24)
- "[Event](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues?utf8=%E2%9C%93&q=label%3AEvent+)" issues keep track of each gathering's participants and notes. e.g.:
  - https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/31
  - https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues/34
- "[Lesson](https://github.com/CERNStudyGroup/cernstudygroup.github.io/issues?utf8=%E2%9C%93&q=label%3ALesson+)" issues list all taught sessions

We could simply have a "Notes" label here and add all notes into the original post (Admin members of the repo have the possibility to edit anyone's posts -- don't abuse! :P). e.g. check out how I'm handling the editing of a book chapter using GitHub issues: https://github.com/cernopendata/opendata.cern.ch/issues/918

Thoughts?

(Also, I think we could re-assign this the label "RFC" or "Request For Comments" rather than "discussion" to keep the latter for content discussions? Does that work? If so, I'll create the label and re-assign this.)

**Comment by twhyntie** [comment]
Ahh... I didn't realise new labels could be created - makes a lot of sense. All sounds good to me :-)

**Comment by RaoOfPhysics** [comment]
Related: For the specification drafts, it might be better to use a Wiki on this repo and save the issues for discussions, instead of drafting the text in a wiki.

**Comment by RaoOfPhysics** [comment]
@twhyntie:

So, a "Meeting notes" label, then?

**Comment by twhyntie** [comment]
@RaoOfPhysics Yeah ("Minutes" sounds a bit dry and non-universal ;-D).

**Comment by RaoOfPhysics** [comment]
Or "Minutes", as long as we're not talking about the detector time windows. :P Can always rename. :)

I'll close this issue then, if there are no further comments. Feel free to re-open the discussion if needed.

**Comment by twhyntie** [comment]
👍

**Comment by RaoOfPhysics** [comment]
Use the button next to the comment to add your reactions. ;) Saves space and collects likes/dislikes.
